#include <bits/stdc++.h>
using namespace std;
typedef long long int ll;
typedef unsigned long long int ull;
typedef pair<ll ,ll> pi;
typedef pair<ll ,ll> pl;
#define modulo 1000000007
#define maxn 1000001
#define PI 3.14159265
#define fast ios_base::sync_with_stdio(0); cin.tie(0); cout.tie(0);

void solve()
{ 
    ll p,q,r;
    ll a,b,c;
    cin >> p >> q >> r;
    cin >> a >> b >> c;

    if (a==p && b==q && c==r)
        cout << "0" << endl; // ( _ _ _ ) ----> ( _ _ _ )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p==b-q && b-q==c-r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( + + + )
    else if (a-p!=0 && b-q!=0 && a-p==b-q && c==r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( + + _ )
    else if (a-p!=0 && c-r!=0 && a-p==c-r && b==q)
        cout << "1" << endl; // ( _ _ _ ) ----> ( + _ + )
    else if (b-q!=0 && c-r!=0 && b-q==c-r && a==p)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ + + )
    else if (a==p && b==q && c-r!=0)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ _ + )
    else if (b==q && c==r && a-p!=0)
        cout << "1" << endl; // ( _ _ _ ) ----> ( + _ _ )
    else if (a==p && c==r && b-q!=0)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ + _ )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && b%q==0 && c%r==0 && a/p==b/q && b/q==c/r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( * * * )
    else if (p!=0 && q!=0 && a%p==0 && b%q==0 && a/p==b/q && c==r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( * * _ )
    else if (p!=0 && r!=0 && a%p==0 && c%r==0 && a/p==c/r && b==q)
        cout << "1" << endl; // ( _ _ _ ) ----> ( * _ * )
    else if (q!=0 && r!=0 && b%q==0 && c%r==0 && b/q==c/r && a==p)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ * * )
    else if (p!=0 && a%p==0 && b==q && c==r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( * _ _ )
    else if (q!=0 && b%q==0 && a==p && c==r)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ * _ )
    else if (r!=0 && c%r==0 && a==p && b==q)
        cout << "1" << endl; // ( _ _ _ ) ----> ( _ _ * )
    else if (p!=0 && q!=0 && r!=0 && r-p!=0 && q-p!=0 && a*q-p*b!=0 && a*r-p*c!=0 && (a*q-p*b)%(q-p)==0 && (a*r-p*c)%(r-p)==0 && (a*q-p*b)/(q-p)==(a*r-p*c)/(r-p) && (b-a)%(q-p)==0 && (c-a)%(r-p)==0 && (b-a)/(q-p)==(c-a)/(r-p))
        cout << "2" << endl; // ( * * * ) ----> ( + + + )
    else if (p!=0 && q!=0 && r!=0 && a*r-p*c!=0 && b*r-q*c!=0 && c%r==0 && (a*r-p*c)%r==0 && (b*r-q*c)%r==0 && (a*r-p*c)/r==(b*r-q*c)/r)
        cout << "2" << endl; // ( * * * ) ----> ( + + _ )
    else if (p!=0 && q!=0 && r!=0 && a*q-p*b!=0 && c*q-r*b!=0 && b%q==0 && (a*q-p*b)%q==0 && (c*q-r*b)%q==0 && (a*q-p*b)/q==(c*q-r*b)/q)
        cout << "2" << endl; // ( * * * ) ----> ( + _ + )
    else if (p!=0 && q!=0 && r!=0 && b*p-q*a!=0 && c*p-r*a!=0 && a%p==0 && (b*p-q*a)%p==0 && (c*p-r*a)%p==0 && (b*p-q*a)/p==(c*p-r*a)/p)
        cout << "2" << endl; // ( * * * ) ----> ( _ + + )
    else if (p!=0 && q!=0 && r!=0 && a*q-p*b!=0 && a*r-p*c!=0 && b%q==0 && c%r==0 && b/q==c/r && (a*q-p*b)%q==0 && (a*r-p*c)%r==0 && (a*q-p*b)/q==(a*r-p*c)/r)
        cout << "2" << endl; // ( * * * ) ----> ( + _ _ )
    else if (p!=0 && q!=0 && r!=0 && b*p-q*a!=0 && b*r-q*c!=0 && a%p==0 && c%r==0 && a/p==c/r && (b*p-q*a)%p==0 && (b*r-q*c)%r==0 && (b*p-q*a)/p==(b*r-q*c)/r)
        cout << "2" << endl; // ( * * * ) ----> ( _ + _)
    else if (p!=0 && q!=0 && r!=0 && c*p-r*a!=0 && c*q-r*b!=0 && a%p==0 && b%q==0 && a/p==b/q && (c*p-r*a)%p==0 && (c*q-r*b)%q==0 && (c*p-r*a)/p==(c*q-r*b)/q)
        cout << "2" << endl; // ( * * * ) ----> ( _ _ + )
    else if (p!=0 && q!=0 && c-r!=0 && q-p!=0 && (a-c+r)%p==0 && (b-c+r)%q==0 && (a-c+r)/p==(b-c+r)/q && a*q-p*b!=0 && (a*q-p*b)%(q-p)==0 && (a*q-p*b)/(q-p)==c-r)
        cout << "2" << endl; // ( * * _ ) ----> ( + + + )
    else if (p!=0 && r!=0 && b-q!=0 && r-p!=0 && (a-b+q)%p==0 && (c-b+q)%r==0 && (a-b+q)/p==(c-b+q)/r && a*r-p*c!=0 && (a*r-p*c)%(r-p)==0 && (a*r-p*c)/(r-p)==b-q)
        cout << "2" << endl; // ( * _ * ) ----> ( + + + )
    else if (q!=0 && r!=0 && a-p!=0 && q-r!=0 && (b-a+p)%q==0 && (c-a+p)%r==0 && (b-a+p)/q==(c-a+p)/r && c*q-r*b!=0 && (c*q-r*b)%(q-r)==0 && (c*q-r*b)/(q-r)==a-p)
        cout << "2" << endl; // ( _ * * ) ----> ( + + + )
    else if (p!=0 && q!=0 && q-p!=0 && a*q-p*b!=0 && (a*q-p*b)%(q-p)==0 && (b-a)%(q-p)==0 && c==r)
        cout << "2" << endl; // ( * * _ ) ----> ( + + _ )
    else if (p!=0 && r!=0 && r-p!=0 && a*r-p*c!=0 && (a*r-p*c)%(r-p)==0 && (c-a)%(r-p)==0 && b==q)
        cout << "2" << endl; // ( * _ * ) ----> ( + _ + )
    else if (q!=0 && r!=0 && r-q!=0 && c*q-r*b!=0 && (c*q-r*b)%(r-q)==0 && (c-b)%(r-q)==0 && a==p)
        cout << "2" << endl; // ( _ * * ) ----> ( _ + + )
    else if (p!=0 && q!=0 && c-r!=0 && b%q==0 && (a-c+r)%p==0 && b/q==(a-c+r)/p && a*q-p*b!=0 && (a*q-p*b)%q==0 && c-r==(a*q-p*b)/q)
        cout << "2" << endl; // ( * * _ ) ----> ( + _ + )
    else if (p!=0 && q!=0 && c-r!=0 && a%p==0 && (b-c+r)%q==0 && a/p==(b-c+r)/q && b*p-q*a!=0 && (b*p-q*a)%p==0 && c-r==(b*p-q*a)/p)
        cout << "2" << endl; // ( * * _ ) ----> ( _ + + )
    else if (p!=0 && r!=0 && b-q!=0 && c%r==0 && (a-b+q)%p==0 && c/r==(a-b+q)/p && a*r-p*c!=0 && (a*r-p*c)%r==0 && b-q==(a*r-p*c)/r)
        cout << "2" << endl; // ( * _ * ) ----> ( + + _ )
    else if (p!=0 && r!=0 && b-q!=0 && a%p==0 && (c-b+q)%r==0 && a/p==(c-b+q)/r && c*p-r*a!=0 && (c*p-r*a)%p==0 && b-q==(c*p-r*a)/p)
        cout << "2" << endl; // ( * _ * ) ----> ( _ + + )
    else if (q!=0 && r!=0 && a-p!=0 && c%r==0 && (b-a+p)%q==0 && c/r==(b-a+p)/q && b*r-q*c!=0 && (b*r-q*c)%r==0 && a-p==(b*r-q*c)/r)
        cout << "2" << endl; // ( _ * * ) ----> ( + + _ )
    else if (q!=0 && r!=0 && a-p!=0 && b%q==0 && (c-a+p)%r==0 && b/q==(c-a+p)/r && c*q-r*b!=0 && (c*q-r*b)%q==0 && a-p==(c*q-r*b)/q)
        cout << "2" << endl; // ( _ * * ) ----> ( + _ + )
    else if (p!=0 && q!=0 && c-r!=0 && a%p==0 && b%q==0 && a/p==b/q)
        cout << "2" << endl; // ( * * _ ) ----> ( _ _ + )
    else if (p!=0 && r!=0 && b-q!=0 && a%p==0 && c%r==0 && a/p==c/r)
        cout << "2" << endl; // ( * _ * ) ----> ( _ + _ )
    else if (q!=0 && r!=0 && a-p!=0 && b%q==0 && c%r==0 && b/q==c/r)
        cout << "2" << endl; // ( _ * * ) ----> ( + _ _ )
    else if (p!=0 && q!=0 && b%q==0 && a*q-p*b!=0 && (a*q-p*b)%q==0 && c==r)
        cout << "2" << endl; // ( * * _ ) ----> ( + _ _ )
    else if (p!=0 && q!=0 && a%p==0 && b*p-q*a!=0 && (b*p-q*a)%p==0 && c==r)
        cout << "2" << endl; // ( * * _ ) ----> ( _ + _ )
    else if (q!=0 && r!=0 && c%r==0 && b*r-q*c!=0 && (b*r-q*c)%r==0 && a==p)
        cout << "2" << endl; // ( _ * * ) ----> ( _ + _ )
    else if (q!=0 && r!=0 && b%q==0 && c*q-r*b!=0 && (c*q-r*b)%q==0 && a==p)
        cout << "2" << endl; // ( _ * * ) ----> ( _ _ + )
    else if (p!=0 && r!=0 && c%r==0 && a*r-p*c!=0 && (a*r-p*c)%r==0 && b==q)
        cout << "2" << endl; // ( * _ * ) ----> ( + _ _ )
    else if (p!=0 && r!=0 && a%p==0 && c*p-r*a!=0 && (c*p-r*a)%p==0 && b==q)
        cout << "2" << endl; // ( * _ * ) ----> ( _ _ + )
    else if (p!=0 && b-q!=0 && (a-b+q)%p==0 && c==r)
        cout << "2" << endl; // ( * _ _ ) ----> ( + + _ )
    else if (p!=0 && c-r!=0 && (a-c+r)%p==0 && b==q)
        cout << "2" << endl; // ( * _ _ ) ----> ( + _ + )
    else if (q!=0 && a-p!=0 && (b-a+p)%q==0 && c==r)
        cout << "2" << endl; // ( _ * _ ) ----> ( + + _ )
    else if (q!=0 && c-r!=0 && (b-c+r)%q==0 && a==p)
        cout << "2" << endl; // ( _ * _ ) ----> ( _ + + )
    else if (r!=0 && a-p!=0 && (c-a+p)%r==0 && b==q)
        cout << "2" << endl; // ( _ _ * ) ----> ( + _ + )
    else if (r!=0 && b-q!=0 && (c-b+q)%r==0 && a==p)
        cout << "2" << endl; // ( _ _ * ) ----> ( _ + + )
    else if (p!=0 && b-q!=0 && c-r!=0 && b-q==c-r && (a-c+r)%p==0 && (a-b+q)%p==0 && (a-c+r)/p==(a-b+q)/p)
        cout << "2" << endl; // ( * _ _ ) ----> ( + + + )
    else if (q!=0 && a-p!=0 && c-r!=0 && a-p==c-r && (b-c+r)%q==0 && (b-a+p)%q==0 && (b-c+r)/q==(b-a+p)/q)
        cout << "2" << endl; // ( _ * _ ) ----> ( + + + )
    else if (r!=0 && a-p!=0 && b-q!=0 && p-a==q-b && (c-b+q)%r==0 && (c-a+p)%r==0 && (c-b+q)/r==(c-a+p)/r)
        cout << "2" << endl; // ( _ _ * ) ----> ( + + + )
    else if (p!=0 && a%p==0 && b-q!=0 && c-r!=0 && b-q==c-r)
        cout << "2" << endl; // ( * _ _ ) ----> ( _ + + )
    else if (q!=0 && b%q==0 && a-p!=0 && c-r!=0 && a-p==c-r)
        cout << "2" << endl; // ( _ * _ ) ----> ( + _ + )
    else if (r!=0 && c%r==0 && a-p!=0 && b-q!=0 && a-p==b-q)
        cout << "2" << endl; // ( _ _ * ) ----> ( + + _ )
    else if (p!=0 && b-q!=0 && a%p==0 && c==r && a-p!=b-q)
        cout << "2" << endl; // ( * _ _ ) ----> ( _ + _ ) 
    else if (p!=0 && c-r!=0 && a%p==0 && b==q && a-p!=c-r)
        cout << "2" << endl; // ( * _ _ ) ----> ( _ _ + )
    else if (q!=0 && a-p!=0 && b%q==0 && c==r && b-q!=a-p)
        cout << "2" << endl; // ( _ * _ ) ----> ( + _ _ )
    else if (q!=0 && c-r!=0 && b%q==0 && a==p && b-q!=c-r)
        cout << "2" << endl; // ( _ * _ ) ----> ( _ _ + )
    else if (r!=0 && a-p!=0 && c%r==0 && b==q && a-p!=c-r)
        cout << "2" << endl; // ( _ _ * ) ----> ( + _ _ )
    else if (r!=0 && b-q!=0 && c%r==0 && a==p && b-q!=c-r)
        cout << "2" << endl; // ( _ _ * ) ----> ( _ + _ )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p==b-q && a-p!=c-r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( + + +1 )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p==c-r && a-p!=b-q)
        cout << "2" << endl; // ( _ _ _ ) ----> ( + +1 + )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && b-q==c-r && b-q!=a-p)
        cout << "2" << endl; // ( _ _ _ ) ----> ( +1 + + )
    else if (a-p!=0 && b-q!=0 && a-p!=b-q && c==r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( +1 + _ )
    else if (a-p!=0 && c-r!=0 && a-p!=c-r && b==q)
        cout << "2" << endl; // ( _ _ _ ) ----> ( + _ +1 )
    else if (b-q!=0 && c-r!=0 && b-q!=c-r && a==p)
        cout << "2" << endl; // ( _ _ _ ) ----> ( _ +1 + )
    else if (a-b!=0 && a-c!=0 && p-q!=0 && p-r!=0 && b*p-a*q!=0 && c*p-r*a!=0 && (b*p-a*q)%(a-b)==0 && (c*p-r*a)%(a-c)==0 && (b*p-a*q)/(a-b)==(c*p-r*a)/(a-c) && (a-b)%(p-q)==0 && (a-c)%(p-r)==0 && (a-b)/(p-q)==(a-c)/(p-r))
        cout << "2" << endl; // ( + + + ) ----> ( * * * )
    else if (c-r!=0 && a-b!=0 && p-q!=0 && b*p-a*q!=0 && (b*p-a*q)%(a-b)==0 && (b*p-a*q)/(a-b)==c-r && (a-b)%(p-q)==0)
        cout << "2" << endl; // ( + + + ) ----> ( * * _ )
    else if (b-q!=0 && p-r!=0 && a-c!=0 && c*p-r*a!=0 && (c*p-r*a)%(a-c)==0 && (c*p-r*a)/(a-c)==b-q && (a-c)%(p-r)==0)
        cout << "2" << endl; // ( + + + ) ----> ( * _ * )
    else if (a-p!=0 && q-r!=0 && b-c!=0 && c*q-r*b!=0 && (c*q-r*b)%(b-c)==0 && (c*q-r*b)/(b-c)==a-p && (b-c)%(q-r)==0)
        cout << "2" << endl; // ( + + + ) ----> ( _ * * )
    else if (a!=0 && b-q!=0 && c-r!=0 && b-q==c-r && p+b-q!=0 && p+c-r!=0 && a%(p+b-q)==0 && a%(p+c-r)==0 && a/(p+b-q)==a/(p+c-r))
        cout << "2" << endl; // ( + + + ) ----> ( * _ _ )
    else if (b!=0 && a-p!=0 && c-r!=0 && a-p==c-r && q+a-p!=0 && q+c-r!=0 && b%(q+a-p)==0 && b%(q+c-r)==0 && b/(q+a-p)==b/(q+c-r))
        cout << "2" << endl; // ( + + + ) ----> ( _ * _ )
    else if (c!=0 && a-p!=0 && b-q!=0 && a-p==b-q && r+a-p!=0 && r+b-q!=0 && c%(r+a-p)==0 && c%(r+b-q)==0 && c/(r+a-p)==c/(r+b-q))
        cout << "2" << endl; // ( + + + ) ----> ( _ _ * )
    else if (r!=0 && c!=0 && a*r-p*c!=0 && b*r-q*c!=0 && (a*r-p*c)%c==0 && (b*r-q*c)%c==0 && (a*r-p*c)/c==(b*r-q*c)/c && c%r==0 && a-b!=0 && p-q!=0 && (a-b)%(p-q)==0 && (a-b)/(p-q)==c/r)
        cout << "2" << endl; // ( + + _ ) ----> ( * * * )
    else if (q!=0 && b!=0 && a*q-p*b!=0 && c*q-r*b!=0 && (a*q-p*b)%b==0 && (c*q-r*b)%b==0 && (a*q-p*b)/b==(c*q-r*b)/b && b%q==0 && a-c!=0 && p-r!=0 && (a-c)%(p-r)==0 && (a-c)/(p-r)==b/q)
        cout << "2" << endl; // ( + _ + ) ----> ( * * * )
    else if (p!=0 && a!=0 && b*p-q*a!=0 && c*p-r*a!=0 && (b*p-q*a)%a==0 && (c*p-r*a)%a==0 && (b*p-q*a)/a==(c*p-r*a)/a && a%p==0 && b-c!=0 && q-r!=0 && (b-c)%(q-r)==0 && (b-c)/(q-r)==a/p)
        cout << "2" << endl; // ( _ + + ) ----> ( * * * )
    else if (a!=0 && b-q!=0 && r!=0 && c!=0 && c%r==0 && a*r-p*c!=0 && (a*r-p*c)%c==0 && (a*r-p*c)/c==b-q && p+b-q!=0 && a%(p+b-q)==0 && a/(p+b-q)==c/r)
        cout << "2" << endl; // ( + + _ ) ----> ( * _ * )
    else if (b!=0 && a-p!=0 && r!=0 && c!=0 && c%r==0 && b*r-q*c!=0 && (b*r-q*c)%c==0 && (b*r-q*c)/c==a-p && q+a-p!=0 && b%(q+a-p)==0 && b/(q+a-p)==c/r)
        cout << "2" << endl; // ( + + _ ) ----> ( _ * * )
    else if (a!=0 && c-r!=0 && q!=0 && b!=0 && b%q==0 && a*q-p*b!=0 && (a*q-p*b)%b==0 && (a*q-p*b)/b==c-r && p+c-r!=0 && a%(p+c-r)==0 && a/(p+c-r)==b/q)
        cout << "2" << endl; // ( + _ + ) ----> ( * * _ )
    else if (c!=0 && a-p!=0 && q!=0 && b!=0 && b%q==0 && c*q-r*b!=0 && (c*q-r*b)%b==0 && (c*q-r*b)/b==a-p && r+a-p!=0 && c%(r+a-p)==0 && c/(r+a-p)==b/q)
        cout << "2" << endl; // ( + _ + ) ----> ( _ * * )
    else if (b!=0 && c-r!=0 && p!=0 && a!=0 && a%p==0 && b*p-q*a!=0 && (b*p-q*a)%a==0 && (b*p-q*a)/a==c-r && q+c-r!=0 && b%(q+c-r)==0 && b/(q+c-r)==a/p)
        cout << "2" << endl; // ( _ + + ) ----> ( * * _ ) 
    else if (c!=0 && b-q!=0 && p!=0 && a!=0 && a%p==0 && c*p-r*a!=0 && (c*p-r*a)%a==0 && (c*p-r*a)/a==b-q && r+b-q!=0 && c%(r+b-q)==0 && c/(r+b-q)==a/p)
        cout << "2" << endl; // ( _ + + ) ----> ( * _ * )
    else if (a-b!=0 && b*p-a*q!=0 && (b*p-a*q)%(a-b)==0 && c==r)
        cout << "2" << endl; // ( + + _ ) ----> ( * * _ )
    else if (a-c!=0 && c*p-r*a!=0 && (c*p-r*a)%(a-c)==0 && b==q)
        cout << "2" << endl; // ( + _ + ) ----> ( * _ * )
    else if (b-c!=0 && c*q-r*b!=0 && (c*q-r*b)%(b-c)==0 && a==p)
        cout << "2" << endl; // ( _ + + ) ----> ( _ * * )
    else if (r!=0 && c%r==0 && a-p!=0 && b-q!=0 && a-p==b-q && a-p!=c-r)
        cout << "2" << endl; // ( + + _ ) ----> ( _ _ * )
    else if (q!=0 && b%q==0 && a-p!=0 && c-r!=0 && a-p==c-r && a-p!=b-q)
        cout << "2" << endl; // ( + _ + ) ----> ( _ * _ )
    else if (p!=0 && a%p==0 && b-q!=0 && c-r!=0 && b-q==c-r && a-p!=b-q)
        cout << "2" << endl; // ( _ + + ) ----> ( * _ _ )
    else if (q!=0 && r!=0 && b!=0 && c!=0 && b%q==0 && c%r==0 && b/q==c/r && a*q-p*b!=0 && a*r-p*c!=0 && (a*q-p*b)%b==0 && (a*r-p*c)%c==0 && (a*q-p*b)/b==(a*r-p*c)/c)
        cout << "2" << endl; // ( + _ _ ) ----> ( * * * )
    else if (p!=0 && r!=0 && a!=0 && c!=0 && a%p==0 && c%r==0 && a/p==c/r && b*p-q*a!=0 && b*r-q*c!=0 && (b*p-q*a)%a==0 && (b*r-q*c)%c==0 && (b*p-q*a)/a==(b*r-q*c)/c)
        cout << "2" << endl; // ( _ + _ ) ----> ( * * * )
    else if (p!=0 && q!=0 && a!=0 && b!=0 && a%p==0 && b%q==0 && a/p==b/q && c*p-r*a!=0 && c*q-r*b!=0 && (c*p-r*a)%a==0 && (c*q-r*b)%b==0 && (c*p-r*a)/a==(c*q-r*b)/b)
        cout << "2" << endl; // ( _ _ + ) ----> ( * * * )
    else if (p!=0 && q!=0 && c-r!=0 && a%p==0 && b%q==0 && a/p==b/q)
        cout << "2" << endl; // ( _ _ + ) ----> ( * * _ )
    else if (p!=0 && r!=0 && b-q!=0 && a%p==0 && c%r==0 && a/p==c/r)
        cout << "2" << endl; // ( _ + _ ) ----> ( * _ * )
    else if (q!=0 && r!=0 && a-p!=0 && b%q==0 && c%r==0 && b/q==c/r)
        cout << "2" << endl; // ( + _ _ ) ----> ( _ * * )
    else if (b-q!=0 && p+b-q!=0 && a%(p+b-q)==0 && c==r)
        cout << "2" << endl; // ( + + _ ) ----> ( * _ _ )
    else if (a-p!=0 && q+a-p!=0 && b%(q+a-p)==0 && c==r)
        cout << "2" << endl; // ( + + _ ) ----> ( _ * _ )
    else if (c-r!=0 && q+c-r!=0 && b%(q+c-r)==0 && a==p)
        cout << "2" << endl; // ( _ + + ) ----> ( _ * _ )
    else if (b-q!=0 && r+b-q!=0 && c%(r+b-q)==0 && a==p)
        cout << "2" << endl; // ( _ + + ) ----> ( _ _ * ) 
    else if (c-r!=0 && p+c-r!=0 && a%(p+c-r)==0 && b==q)
        cout << "2" << endl; // ( + _ + ) ----> ( * _ _ )
    else if (a-p!=0 && r+a-p!=0 && c%(r+a-p)==0 && b==q)
        cout << "2" << endl; // ( + _ + ) ----> ( _ _ * )
    else if (q!=0 && b!=0 && b%q==0 && a*q-p*b!=0 && (a*q-p*b)%b==0 && c==r)
        cout << "2" << endl; // ( + _ _ ) ----> ( * * _ )
    else if (r!=0 && c!=0 && c%r==0 && a*r-p*c!=0 && (a*r-p*c)%c==0 && b==q)
        cout << "2" << endl; // ( + _ _ ) ----> ( * _ * )
    else if (p!=0 && a!=0 && a%p==0 && b*p-q*a!=0 && (b*p-q*a)%a==0 && c==r)
        cout << "2" << endl; // ( _ + _ ) ----> ( * * _ )
    else if (r!=0 && c!=0 && c%r==0 && b*r-q*c!=0 && (b*r-q*c)%c==0 && a==p)
        cout << "2" << endl; // ( _ + _ ) ----> ( _ * * )
    else if (p!=0 && a!=0 && a%p==0 && c*p-r*a!=0 && (c*p-r*a)%a==0 && b==q)
        cout << "2" << endl; // ( _ _ + ) ----> ( * _ * )
    else if (q!=0 && b!=0 && b%q==0 && c*q-r*b!=0 && (c*q-r*b)%b==0 && a==p)
        cout << "2" << endl; // ( _ _ + ) ----> ( _ * * )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && b%q==0 && c%r==0 && a/p==b/q && a/p!=c/r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( * * *2 )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && b%q==0 && c%r==0 && a/p!=b/q && a/p==c/r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( * *2 * )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && b%q==0 && c%r==0 && b/q==c/r && a/p!=c/r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( *2 * * )
    else if (p!=0 && q!=0 && a%p==0 && b%q==0 && a/p!=b/q && c==r)
        cout << "2" << endl; // ( _ _ _ ) ----> ( *2 * _ )
    else if (p!=0 && r!=0 && a%p==0 && c%r==0 && a/p!=c/r && b==q)
        cout << "2" << endl; // ( _ _ _ ) ----> ( *2 _ * )
    else if (q!=0 && r!=0 && b%q==0 && c%r==0 && b/q!=c/r && a==p)
        cout << "2" << endl; // ( _ _ _ ) ----> ( _ *2 * )
    else if (q!=0 && a-p!=0 && b%q==0 && c==r && a-p!=b-q)
        cout << "2" << endl; // ( + _ _ ) ----> ( _ * _ )
    else if (r!=0 && a-p!=0 && c%r==0 && b==q && a-p!=c-r)
        cout << "2" << endl; // ( + _ _ ) ----> ( _ _ * )
    else if (p!=0 && b-q!=0 && a%p==0 && c==r && a-p!=b-q)
        cout << "2" << endl; // ( _ + _ ) ----> ( * _ _ )
    else if (r!=0 && b-q!=0 && c%r==0 && a==p && b-q!=c-r)
        cout << "2" << endl; // ( _ + _ ) ----> ( _ _ * )
    else if (p!=0 && c-r!=0 && a%p==0 && b==q && a-p!=c-r)
        cout << "2" << endl; // ( _ _ + ) ----> ( * _ _ )
    else if (q!=0 && c-r!=0 && b%q==0 && a==p && b-q!=c-r)
        cout << "2" << endl; // ( _ _ + ) ----> ( _ * _ )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p!=c-r && a-p==b-q-c+r)
        cout << "2" << endl; // ( + + _ ) ----> ( _ +1 +1 )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && b-q!=c-r && b-q==a-p-c+r)
        cout << "2" << endl; // ( + + _ ) ----> ( +1 _ +1 )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && b-q!=c-r && c-r==a-p-b+q)
        cout << "2" << endl; // ( + _ + ) ----> ( +1 +1 _ )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && b-q!=a-p && a-p==c-r-b+q)
        cout << "2" << endl; // ( + _ + ) ----> ( _ +1 +1 )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p!=c-r && c-r==b-q-a+p)
        cout << "2" << endl; // ( _ + + ) ----> ( +1 +1 _ )
    else if (a-p!=0 && b-q!=0 && c-r!=0 && a-p!=b-q && b-q==c-r-a+p)
        cout << "2" << endl; // ( _ + + ) ----> ( +1 _ +1 )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && c%r==0 && a/p!=c/r && c*q!=0 && (b*r)%(c*q)==0 && a/p==(b*r)/(c*q))
        cout << "2" << endl; // ( * * _ ) ----> ( _ *1 *1 )
    else if (p!=0 && q!=0 && r!=0 && b%q==0 && c%r==0 && b/q!=c/r && c*p!=0 && (a*r)%(c*p)==0 && b/q==(a*r)/(c*p))
        cout << "2" << endl; // ( * * _ ) ----> ( *1 _ *1 )
    else if (p!=0 && q!=0 && r!=0 && c%r==0 && b%q==0 && c/r!=b/q && b*p!=0 && (a*q)%(b*p)==0 && c/r==(a*q)/(b*p))
        cout << "2" << endl; // ( * _ * ) ----> ( *1 *1 _ )
    else if (p!=0 && q!=0 && r!=0 && a%p==0 && b%q==0 && a/p!=b/q && b*r!=0 && (c*q)%(b*r)==0 && a/p==(c*q)/(b*r))
        cout << "2" << endl; // ( * _ * ) ----> ( _ *1 *1 )
    else if (p!=0 && q!=0 && r!=0 && c%r==0 && a%p==0 && c/r!=a/p && q*a!=0 && (b*p)%(q*a)==0 && c/r==(b*p)/(q*a))
        cout << "2" << endl; // ( _ * * ) ----> ( *1 *1 _ )
    else if (p!=0 && q!=0 && r!=0 && b%q==0 && a%p==0 && b/q!=a/p && r*a!=0 && (c*p)%(r*a)==0 && b/q==(c*p)/(r*a))
        cout << "2" << endl; // ( _ * * ) ----> ( *1 _ *1 )
    else
        cout << "3" << endl; 
}

int main()
{
    // #ifndef ONLINE_JUDGE
    //     freopen("input.txt","r",stdin);
    //     freopen("output.txt","w",stdout);
    // #endif
    fast;
    int t;
    cin>>t;
    //t=1;
    while(t--)
    {
        solve();
    }
}